# Generated by Django 2.0 on 2018-05-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job51',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=256, verbose_name='名称')),
                ('company', models.CharField(max_length=512, verbose_name='公司')),
                ('address', models.CharField(max_length=512, verbose_name='地址')),
                ('wages', models.CharField(max_length=256, verbose_name='薪资')),
                ('date', models.CharField(max_length=256, verbose_name='发布日期')),
                ('jobname', models.CharField(max_length=256, verbose_name='职位类别')),
                ('joburl', models.CharField(max_length=512, verbose_name='链接')),
                ('jobtxt', models.CharField(blank=True, max_length=512, verbose_name='岗位职责')),
                ('jobaddress', models.CharField(blank=True, max_length=256, verbose_name='上班地点')),
            ],
            options={
                'verbose_name': '51job数据表',
                'verbose_name_plural': '51job数据表',
            },
        ),
    ]
