# Generated by Django 2.0 on 2018-05-10 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('msg_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
                ('msg_content', models.TextField(max_length=128, verbose_name='留言内容')),
                ('msg_email', models.EmailField(max_length=254, verbose_name='邮件')),
                ('msg_title', models.CharField(max_length=32, verbose_name='标题')),
            ],
            options={
                'verbose_name': '留言结构表',
                'verbose_name_plural': '留言结构表',
            },
        ),
    ]
