# Generated by Django 2.0 on 2018-05-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='msg_sex',
            field=models.CharField(choices=[('B', '男'), ('G', '女')], default=1, max_length=10, verbose_name='性别'),
            preserve_default=False,
        ),
    ]
